ping_job:
  every:
    - "10s"
    - first_in => '5s'
  class: PingJob
  description: "Ping worker."
refreshing_hp_image_job:
  cron:
    - "0 08 * * * Europe/Prague"
    - first_in => '5s'
  class: RefreshImageJob
  description: "Refreshing images."

