ping_job:
  every:
    - "10s"
    - first_in => '5s'
  class: PingJob
  description: "Ping worker."
new_image_job:
  cron:
    - "0 08 * * *"
    - first_in => '10s'
  class: NewImageJob
  description: "Refreshing images."

