#new_image_job:
#  cron: "0 08 * * * Europe/Prague"
#  class: NewImageJob
#  description: "Refreshing images."
#ping_job:
#  every:
#    - "10s"
#    - first_in => '5s'
#  class: PingJob
#  description: "Ping worker."

